### ISSUE TITLE
请求保命代码更新

### ISSUE THREAD

**Issue by SamZong233** [Avenshy/majsoul_mod_plus#108]
0.11.30.w停服更新后无法进入大厅
浏览器控制台提示

code.js:32666 Uncaught TypeError: Cannot use 'in' operator to search for 'owner' in null
    at F.<computed> [as createComp] (code.js:32666:61)
    at F.<computed> [as createComp] (code.js:32665:52)
    at F.<computed> [as createComp] (code.js:32665:52)
    at F.<computed> [as createComp] (code.js:32665:52)
    at F.<computed> [as createComp] (code.js:32665:52)
    at F.<computed> [as createComp] (code.js:32665:52)
    at E.<computed> [as createView] (code.js:32599:88)
    at E.<computed> [as loadUI] (code.js:32623:36)
    at F.<computed>.<computed> [as createChildren] (code.js:138839:31)
    at F (code.js:30535:31)

**Comment by Avenshy** [comment]
woc

**Comment by imgodkillerliu** [comment]
> woc

大佬，刷新缓存不能自动应用更新的safecode

**Comment by SamZong233** [comment]
> woc

> > woc
> 
> 大佬，刷新缓存不能自动应用更新的safecode

jsdelivr上的js尚未更新

**Comment by AsakuraHitomi** [comment]
> > woc
> 
> 大佬，刷新缓存不能自动应用更新的safecode

目前还是不能

**Comment by Avenshy** [comment]
jsdelivr缓存太久了，新上传了一个用githack

**Comment by dangdang556** [comment]
11.32w版本，保命代码更新了吗
