### ISSUE TITLE
请求保命代码更新

### ISSUE THREAD

**Issue by core37** [Avenshy/majsoul_mod_plus#116]

**Comment by core37** [comment]
Uncaught TypeError: Cannot set properties of null (setting 'clickHandler')
    at P.<computed>.<computed> [as onCreate] (code.js:1:2700276)
    at F.<computed>.<computed> [as _onload] (code.js:1:2433574)
    at F.run (code.js:1:785030)
    at z.<computed> [as _update] (code.js:1:782068)
    at F.run (code.js:1:785030)
    at z.<computed> [as _update] (code.js:1:781918)
    at M.<computed> [as render] (code.js:1:895054)
    at M.<computed> [as _loop] (code.js:1:894398)
    at h (code.js:1:722272)
