### ISSUE TITLE
titles and bond

### ISSUE THREAD

**Issue by mianmur** [Avenshy/majsoul_mod_plus#59]
after every game i get a bond level up screen 

also cannot change title
gives error:
```
userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=480ccb45-bc96-41ce-8fac-4299bdce6a59:4593 
        
       Uncaught ReferenceError: g is not defined
    at y.changeTitle (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=480ccb45-bc96-41ce-8fac-4299bdce6a59:4593:54)
    at y.<anonymous> (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=480ccb45-bc96-41ce-8fac-4299bdce6a59:4565:99)
    at S.run (code.js:1:599146)
    at x.<computed> [as onMouse] (code.js:1:1252578)
    at S.<computed> [as runWith] (code.js:1:599499)
    at J.<computed> [as event] (code.js:1:596991)
    at S.<computed> [as sendEvents] (code.js:1:633155)
    at S.<computed> [as onMouseUp] (code.js:1:634893)
    at S.<computed> [as onMouseUp] (code.js:1:629196)
    at S.<computed> [as check] (code.js:1:629769)
```

**Comment by mianmur** [comment]
also saved items do not display until i change tablecloth/tiles and change back to what i had before

**Comment by Avenshy** [comment]
> after every game i get a bond level up screen

it's bug 

i will fix after test negative for the coronavirus

---

> also cannot change title

sorry my bad :(

please find `MMP.settings.title = g;` change into `MMP.settings.title = B;`

---

> also saved items do not display until i change tablecloth/tiles and change back to what i had before

it's bug 

i will fix after test negative for the coronavirus

**Comment by mianmur** [comment]
found the line and change it thank you

get well soon
