### ISSUE TITLE
Cannot enter match as of version 0.10.210.w (following February 22nd maintenance)

### ISSUE THREAD

**Issue by adityahdes** [Avenshy/majsoul_mod_plus#69]
Tested in both Firefox and Chrome. Mod works in menus / outside of match, but game freezes at around 40% when trying to enter mahjong match. Following error appears in console in Firefox:
```
Uncaught TypeError: V is null
    _initFunc moz-extension://938fa805-bf05-43a5-bf08-0ebb5212d8c9/userscripts/雀魂Mod_Plus.user.js?id=22ef9038-d672-441f-bfac-bb7ddfbdfb90:6318
    onCreate moz-extension://938fa805-bf05-43a5-bf08-0ebb5212d8c9/userscripts/雀魂Mod_Plus.user.js?id=22ef9038-d672-441f-bfac-bb7ddfbdfb90:6229
    $j[1]][$V[828] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    run https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $v[555] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    run https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $v[555] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $3[38] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $N[319] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    J https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
   ...
    J https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
eval:6318:69
    _initFunc moz-extension://938fa805-bf05-43a5-bf08-0ebb5212d8c9/userscripts/雀魂Mod_Plus.user.js?id=22ef9038-d672-441f-bfac-bb7ddfbdfb90:6318
    onCreate moz-extension://938fa805-bf05-43a5-bf08-0ebb5212d8c9/userscripts/雀魂Mod_Plus.user.js?id=22ef9038-d672-441f-bfac-bb7ddfbdfb90:6229
    $j[1]][$V[828] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    run https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $v[555] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    run https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $v[555] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $3[38] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    $N[319] https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    J https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
    (Async: FrameRequestCallback)
    J https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
   ...
    (Async: FrameRequestCallback)
    J https://mahjongsoul.game.yo-star.com/v0.10.210.w/code.js:1
```
Following error in chrome:
```
Uncaught TypeError: Cannot set properties of null (setting 'clickHandler')
    at i._initFunc (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=ece6f9ca-48db-4e6f-a4af-a30c0977fd44:6318:67)
    at i.onCreate (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=ece6f9ca-48db-4e6f-a4af-a30c0977fd44:6229:50)
    at P.<computed>.<computed> [as _onload] (code.js:1:2300425)
    at P.run (code.js:1:722897)
    at B.<computed> [as _update] (code.js:1:719944)
    at P.run (code.js:1:722897)
    at B.<computed> [as _update] (code.js:1:719853)
    at h.<computed> [as render] (code.js:1:829492)
    at h.<computed> [as _loop] (code.js:1:828839)
    at J (code.js:1:660629)
```
![image](https://user-images.githubusercontent.com/41651976/220632495-f653d212-088f-4f00-a68d-048e93e12b39.png)

**Comment by Nineball89** [comment]
guess we need to wait for the save code update
