### ISSUE TITLE
Uncaught TypeError: Cannot set properties of null (setting 'clickHandler')

### ISSUE THREAD

**Issue by 838239178** [Avenshy/majsoul_mod_plus#70]
```
[雀魂mod_plus] 配置已读取：
userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:1112 MajsoulModPlus
userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6998 [雀魂mod_plus] 等待游戏启动

code.js:1 Warning!,this class[MiniAdpter] already exist: Object

sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:1:286

www.facebook.com/tr/?id=511764882872601&ev=fb_page_view&dl=https%3A%2F%2Fgame.maj-soul.com%2F1%2F&rl=&if=false&ts=1677144539152&sw=1920&sh=1080&at=:1 Failed to load resource: net::ERR_FAILED

userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6998 [雀魂mod_plus] 等待游戏启动
code.js:1 loadProto finished
code.js:1 Wrapper is {"fields":{"name":{"type":"string","id":1},"data":{"type":"bytes","id":2}}}
userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6985 [雀魂mod_plus] 启动完毕!!!
/1/chs_t/extendRes/emo/e200007/16.png:1 Failed to load resource: the server responded with a status of 404 ()
userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6318 Uncaught TypeError: Cannot set properties of null (setting 'clickHandler')
    at i._initFunc (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6318:67)
    at i.onCreate (userscript.html?name=%25E9%259B%2580%25E9%25AD%2582Mod_Plus.user.js&id=57c1fcec-4f58-4b1c-a05a-6aaf4024fc34:6229:50)
    at P.<computed>.<computed> [as _onload] (code.js:1:2300425)
    at P.run (code.js:1:722897)
    at B.<computed> [as _update] (code.js:1:719944)
    at P.run (code.js:1:722897)
    at B.<computed> [as _update] (code.js:1:719853)
    at h.<computed> [as render] (code.js:1:829492)
    at h.<computed> [as _loop] (code.js:1:828839)
    at J (code.js:1:660629)
```

**Comment by 838239178** [comment]
已更新
